// ============================================================
//  TOPIC LIST
//  Edit freely: add, delete, rewrite. Order does NOT matter —
//  each topic is identified by a hash of its text, so shuffling
//  the list will not corrupt your "already used" history.
//  (Renaming a topic makes it count as a brand-new topic.)
// ============================================================

export const TOPICS = [
  // — Science & nature —
  "Deep sea gigantism: why things get huge in the dark",
  "How do noise-cancelling headphones actually work?",
  "The immortal jellyfish",
  "Why is the sky blue, and why are sunsets red?",
  "Tardigrades: the animal that survives space",
  "The Great Oxidation Event — the worst pollution disaster ever",
  "How does anaesthesia work? (Nobody fully knows)",
  "Bioluminescence",
  "The Voyager Golden Record",
  "Why do we sleep?",
  "The chemistry of why bread smells good",
  "Slime moulds can solve mazes",
  "How GPS has to account for relativity",
  "Ant colonies as a single organism",
  "The mystery of ball lightning",
  "Why can't we cure the common cold?",
  "Cephalopod intelligence",
  "The Fermi Paradox",
  "How vaccines were invented",
  "The physics of a curveball",
  "Fungal networks between trees",
  "Why does time feel faster as you age?",
  "The sound of the loudest noise ever recorded (Krakatoa)",
  "Mantis shrimp vision",

  // — History —
  "The Great Emu War",
  "The Dancing Plague of 1518",
  "The most successful pirate in history was a woman",
  "The Radium Girls",
  "How the Rosetta Stone was decoded",
  "The Antikythera mechanism",
  "The Cadaver Synod: the trial of a dead pope",
  "The Halifax Explosion",
  "A day in the life of a Roman citizen",
  "The tulip mania bubble",
  "How the Silk Road actually worked",
  "The Library of Alexandria: what was really lost",
  "The Salem witch trials",
  "The invention of zero",
  "The Molasses Flood of 1919",
  "The Christmas Truce of 1914",
  "The woman who sold the Eiffel Tower (twice)",
  "The Voynich manuscript",
  "The Year Without a Summer",
  "Shackleton's Endurance expedition",
  "The history of your own surname",
  "The Great Stink of London",
  "How the Titanic sank, minute by minute",
  "The rise and fall of the Aztec capital",

  // — Culture, food, and everyday things —
  "The history of the QWERTY keyboard",
  "Why do we clink glasses?",
  "How Coca-Cola invented modern Santa Claus",
  "The origin of the handshake",
  "Why is the wedding dress white?",
  "The invention of the sandwich",
  "Why do we say 'hello' on the phone?",
  "The global history of noodles",
  "How chess spread across the world",
  "The story of a single spice (pick one)",
  "Why do British and American English differ?",
  "The history of the colour purple",
  "The invention of the modern supermarket",
  "How ice cream conquered the world",
  "The origin of playing card designs",
  "Why do we blow out birthday candles?",
  "The Michelin Guide was a tyre advert",
  "The history of coffee houses",
  "How did the necktie happen?",
  "The strange history of breakfast cereal",
  "Where do country flags' designs come from?",
  "The rules of a sport neither of us understands",

  // — Technology & the internet —
  "How does the internet physically cross oceans?",
  "The story of the first computer bug",
  "Why is it so hard to make a good CAPTCHA?",
  "The history of emoji",
  "How does a microwave heat food?",
  "The Y2K problem: overblown or narrowly averted?",
  "How does Shazam identify a song in seconds?",
  "The rise and death of Flash",
  "How does a lock work, and how are they picked?",
  "The most expensive software bug in history",
  "Why do phone chargers keep changing?",
  "How does Wikipedia stay (mostly) accurate?",
  "The history of the video game crash of 1983",
  "How does a self-checkout know you didn't scan it?",
  "The invention of the shipping container",
  "How does an MRI work?",
  "The story of one font (Comic Sans, Helvetica, etc.)",
  "How search engines actually rank pages",

  // — Mysteries & unsolved —
  "The disappearance of the Roanoke colony",
  "The Dyatlov Pass incident",
  "The Wow! Signal",
  "The Bermuda Triangle: the boring true explanation",
  "The Somerton Man",
  "D. B. Cooper",
  "The Zodiac ciphers",
  "The Lost Cosmonauts theory",
  "The Mary Celeste",
  "The Nazca Lines",
  "Unsolved art heists",
  "The Bloop and other unexplained ocean sounds",

  // — Art, music & film —
  "Why does minor key sound sad?",
  "The story behind one famous painting",
  "How film scores manipulate you",
  "The Wilhelm Scream",
  "How was stop-motion animation made before computers?",
  "The most sampled drum break in history",
  "Why do movie trailers all sound the same?",
  "The history of the music video",
  "The forgery that fooled the art world",
  "How colour was added to early film",
  "The Beatles' last rooftop concert",
  "Why did buildings suddenly go brutalist?",
  "The evolution of the horror movie monster",
  "One-hit wonders: what happened next",

  // — Human behaviour & the mind —
  "The Stanford Prison Experiment and why it's disputed",
  "Why do we get déjà vu?",
  "The placebo effect (and the nocebo effect)",
  "How reliable is eyewitness memory?",
  "The bystander effect",
  "Why do people believe conspiracy theories?",
  "The psychology of queuing",
  "Colour perception across languages",
  "Why is yawning contagious?",
  "The science of habit formation",
  "Why do we find some faces attractive?",
  "The Dunning–Kruger effect",
  "How do people learn a second language?",
  "The psychology of collecting",
  "The house money effect",
  " The illusion of transparency",

  // — Places & geography —
  "The country that no longer exists (pick one)",
  "How time zones were invented",
  "The most isolated inhabited place on Earth",
  "Why are borders so weirdly straight in some places?",
  "The city built entirely underground",
  "How the Netherlands took land from the sea",
  "Micronations",
  "The world's most dangerous hiking trail",
  "How the London Underground map changed map design forever",
  "The town that moved",
  "The Sahara was green 10,000 years ago",
  "Why are so many capitals not the biggest city?",

  // — Odd & delightful —
  "Competitive events you've never heard of",
  "The history of the vending machine",
  "Animals that have been put on trial",
  "The world's rarest colour",
  "The most complicated board game ever made",
  "Extremely specific world records",
  "The economics of an all-you-can-eat buffet",
  "How do they film nature documentaries?",
  "Fictional languages and the people who speak them",
  "The strangest laws still on the books",
  "Failed utopian communities",
  "The history of the theme park ride",
  "Why do cats purr?",
  "The most elaborate prank in history",
  "Sound effects: how foley artists work",
  "The economics of a vending-machine-only country",

  // — Aaron & Chloë specials —
  "The year you were born: what else was happening",
  "A full tour of a city you've never been to but want us to go to",
  "Make the case for your most controversial opinion",
  "The history of the town/village you grew up in",
  "Sell me on a hobby you want us both to take up",
];
